name: Check for git LFS pointers

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Search for oids in modified lines
      run: |
        git diff -U0 --ignore-all-space $(git merge-base origin/${{ github.event.pull_request.base.ref }} ${{ github.event.pull_request.head.sha }}) \
        | grep "^oid sha236" \
        || ( echo "No pointers found!" ; exit 0 ) \
        && ( echo "Git LFS pointers found; not allowed to add LFS files to Trilinos!" ; exit 1)
