name: Check for git LFS pointers

on:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      with:
        fetch-depth: 0

    - name: Search for oids in modified lines
      run: |
        $GITHUB_WORKSPACE/commonTools/test/utilities/check-lfs-oids.sh \
        origin/${{ github.event.pull_request.base.ref }} \
        ${{ github.event.pull_request.head.sha }}
