name: Spack-nonblocking-PR

on:
  pull_request:
    types:
      - opened
      - synchronize
  pull_request_review:
    types: 
      - submitted
  workflow_dispatch:

jobs:
  triloamd01-spack:
    runs-on: [self-hosted, triloamd01]
    steps:
      - name: module list
        shell: bash
        run: |
          bash -l -c "module list"
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}
      - name: make dirs
        working-directory: /
        run: |
          mkdir -p /home/Trilinos/src/Trilinos
          mkdir -p /home/Trilinos/build
      - name: Clone Trilinos
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: gh pr checkout
        shell: bash -lo pipefail {0}
        run: |
          cd $GITHUB_WORKSPACE
          echo $GITHUB_WORKSPACE 
          gh pr checkout ${{ github.event.number }}
          spack develop --no-clone --path $GITHUB_WORKSPACE trilinos@develop+test
          spack add trilinos@develop+test
          spack concretize -f
          spack install --keep-stage
          cd $(spack location --build-dir trilinos@develop+test)
          ctest -D Experimental --overwrite SubmitURL=https://sems-cdash-son.sandia.gov/cdash/submit.php?project=Trilinos || exit 0
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          GH_TOKEN: ${{ github.token }}
