name: PR-gcc-openmpi

on:
  pull_request:
    types:
      - labeled
      - opened
      - synchronize
    branches:
    - master
    - develop
  workflow_dispatch:

jobs:
  trilogpu02-gcc:
    runs-on: [self-hosted, trilogpu02]
    container:
      image: registry-ex.sandia.gov/trilinos-project/trilinos-containers/rhel8/trilinos-pr-env:gcc-8.5.0
      options: --hostname trilinos-container-gcc-8
    steps:
      - name: env
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          env
      - name: module list
        shell: bash
        run: |
          bash -l -c "module list"
          printenv PATH
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}
      - name: make dirs
        working-directory: /
        run: |
          mkdir -p /home/Trilinos/src/Trilinos
          mkdir -p /home/Trilinos/build
      - name: clone trilinos
        uses: actions/checkout@v4
        with:
          path: /home/Trilinos/src/Trilinos
      - name: Repo status
        working-directory: /home/Trilinos/src/Trilinos
        run: |
          ls -lhat
          git status
          git branch -vv
      - name: get dependencies
        working-directory: /home/Trilinos/src/Trilinos/packages/framework
        run: |
          bash -l -c "./get_dependencies.sh --container"
      - name: Generate PR cmake fragment
        working-directory: /home/Trilinos/build
        run: |
          bash -l -c "source /home/Trilinos/src/Trilinos/packages/framework/GenConfig/gen-config.sh rhel8_gcc-openmpi_debug_shared_no-kokkos-arch_no-asan_complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables --cmake-fragment PR-configuration.cmake /home/Trilinos/src/Trilinos"
      - name: Generate enable packages cmake fragment
        working-directory: /home/Trilinos/build
        run: |
          bash -l -c "TRILINOS_DIR=/home/Trilinos/src/Trilinos /home/Trilinos/src/Trilinos/commonTools/framework/get-changed-trilinos-packages.sh HEAD develop package-enables.cmake ctest-labels.cmake"
      - name: configure trilinos
        working-directory: /home/Trilinos/build
        run: |
          bash -l -c "cmake -C PR-configuration.cmake -C package-enables.cmake /home/Trilinos/src/Trilinos"
      - name: CMakeCache.txt
        if: always()
        working-directory: /home/Trilinos/build
        run: |
          bash -l -c "cat CMakeCache.txt"
      - name: build trilinos
        working-directory: /home/Trilinos/build
        run: bash -l -c "make -j8"
      - name: ctest
        working-directory: /home/Trilinos/build
        run: bash -l -c "ctest -j2"
