name: 'Prohibited Strings'

on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'develop'
      - 'master'

jobs:
  mpi_comm_world:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: file_changes
        uses: trilom/file-changes-action@v1.2.4
        with:
          output: ' '
          fileOutput: ' '

      - name: Show files changed
        run: echo '${{ steps.file_changes.outputs.files}}'

      - name: Find illegal MPI_COMM_WORLD strings
        run: |
          files=$(grep -l MPI_COMM_WORLD ${{steps.file_changes.outputs.files}} | grep packages/)
          if [ -n "${files}" ]
          then
            echo -e "\n#########################################################################"
            echo -e "The following changed files contain MPI_COMM_WORLD, which is not allowed (xSDK policy M3):"
            echo -e "${files}"
            echo -e "#########################################################################"
            exit 1
          else
            echo "MPI_COMM_WORLD not found; PASS"
          fi
